apiVersion: v1
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: "jenkins_cicd_techforce_pvc"
  namespace: "{{ .Values.namespace }}"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "{{ .Values.storageclass }}"
  resources:
    requests:
      storage: "{{ .Values.master.storagecapacity }}"
