apiVersion: v1
kind: Service
metadata:
    name: jenkins_svc_cicd_techforce
    namespace: {{ .Values.namespace }}
spec:
    selector:
        app: jenkins_cicd_techforce
    ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
    - name: sync
      port: 50000
      protocol: TCP
      targetPort: 50000
